variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  CTEST_PARALLEL_LEVEL: 4

image: gepgitlab.laas.fr:4567/loco-3d/crocoddyl

test:
  script:
    - cmake .
    - make
    - make test || ctest -VV

format:
  script:
    - isort -c
    - flake8 .
    - yapf -dr .
