ddp:
  stop_criteria:
    tol: 1e-7
    max_iter: 15
  regularization:
    levenberg_marquard:
      mu0: 1e-8
      inc_rate: 10.
      dec_rate: 0.5
    value_function:
      mu0: 0.
      inc_rate: 10.
      dec_rate: 0.5
  line_search:
    alpha0: 1.
    min_stepsize: 1e-3
    inc_rate: 3.
    dec_rate: 0.5
    armijo_condition: 1e-3
    change_ub: 100.
  record: True
  print: True